### ISSUE TITLE
**** Important **** Read this please

### ISSUE THREAD

**Issue by Uptechai** [logerzhu/simple-graphql#4]
Dear @logerzhu,

I hope this message finds you well. I recently came across your impressive product ad model published on Replicate.com, and I must say that I am truly amazed by its performance and capabilities. Your model has the potential to greatly benefit my projects, and I am writing to kindly request if you would consider sharing the code and resources for this model on GitHub.

I would be immensely grateful for your kind consideration of my request. I am looking forward to hearing from you soon and exploring the potential of your incredible model.

Thank you very much for your time and effort.

Best regards

**Comment by logerzhu** [comment]
Thank you for your kind words about my ad-inpaint model on Replicate.com.

However, I must clarify that the ad-inpaint model was developed specifically for a client's needs and is currently being used for a trial period. The model was uploaded to Replicate.com as a demonstration of the capabilities only.

**Comment by Uptechai** [comment]
> 

Dear @logerzhu,

Thank you for your response to my request for the code. I understand that the model was developed specifically for a client and is currently being used for a trial period. I would like to inquire if you are available to develop a similar model for me. I am willing to pay, and I would appreciate it if you could let me know what your estimated cost would be.

Thank you for your time and consideration, and I look forward to hearing from you soon.

Best regards

**Comment by logerzhu** [comment]
This model was planned to be offered as a buyout solution to the client. However, the client has not yet made any payments, and I am currently working on convincing them to purchase the solution.

The buyout solution is currently priced at $10,000 USD, including one month of technical support. During the support period, I will continue to test and optimize the model, but I cannot guarantee that it will produce better results.

If you are interested in purchasing the solution, please let me know, and I can provide you with more details.

**Comment by Uptechai** [comment]
I tried your model a few more times and I realized that it isn't really doing good on prompts which contain keywords like: kitchen, bathroom...your model works better on natural prompts. Nethertheless i am pretty sure you will handle this problem. 
I am wondering if you already took notize about a tool called flair.ai? It´s providing basically the same functionality as your model but more advanced. 

Are you interested in working together in building a similar tool to flair.ai. I currently work on my personal website www.uptechai.com trying to build a similar tool to flair and pebbely. I am pretty sure flair is taking advantage of depth2img, since the objects you can add in the image have a black background and white borders, what do you think?

I am looking forward hearing from you!

**Comment by logerzhu** [comment]
I appreciate your feedback and the depth2img  really give me some idea of the image generation control. 
I have change the base inpaint model to support more scene prompt and also compose the depth control logic.
Hope it meets your expectations now.

btw, my personal email is loger.zhu at gmail.com.

**Comment by Uptechai** [comment]
Hi logerzhu,

Your model works good now! I'm curious about how you manage to keep the input image unchanged and prevent any attachments to it. May you share a little more about your approach to this? It would be great to learn from your expertise in this area.

Thanks, I look forward to hearing back from you!

Best

**Comment by logerzhu** [comment]
For your question, I used ControlNet to control the inpainting effect. ControlNet has different control types, and by understanding them, you can try preprocessing the control image to get better results.

**Comment by Uptechai** [comment]
Thanks for your response. Will you keep your model on replicate public for the next time? If so, I would like to embed your API into my website. I also came across this project which you might find interresting: https://github.com/sail-sg/EditAnything

**Comment by logerzhu** [comment]
I will keep the ad-inpaint model public for at least six months. However, please do not use `regen_prompt=True` when calling the API as I am currently using my personal account key for the ChatGPT API for demonstration purposes only.

When calling the API, please specify the version number as I am still debugging some parameters and integrating new ideas. The parameters may change frequently.

Regarding EditAnything, I am curious about how you plan to use it. When generating advertising images, I assume you will not refer to the layout of the initial uploaded product image.
