### ISSUE TITLE
Replicate Ad inpaint model @logerzhu

### ISSUE THREAD

**Issue by Uptechai** [logerzhu/simple-graphql#5]
Dear @logerzhu,

I hope this message finds you well. I recently came across your impressive product ad model published on Replicate.com, and I must say that I am truly amazed by its performance and capabilities. Your model has the potential to greatly benefit my projects, and I am writing to kindly request if you would consider sharing the code and resources for this model on GitHub.

I would be immensely grateful for your kind consideration of my request. I am looking forward to hearing from you soon and exploring the potential of your incredible model.

Thank you very much for your time and effort.

Best regards

**Comment by logerzhu** [comment]
Unrelated to this project.
